# Site settings
title: "Soda Theme"
subtitle: "I love Soda."
description: "This is a site description << Soda Theme"
url: "http://yourdomain.com"
baseurl: ""
logo:
cover_image:
twitter: "yiming_t"
google_analytics: "UA-XXXXX-X"

author:
  name: "Yiming Tang"
  email: "yimingnju@gmail.com"
  twitter: "yiming_t"
  github: "yimingtang"
  bio: "I'm studying Software Engineering at Nanjing University. I also an iOS developer. <a href='http://lightmail.im'>I made LightMail</a>."
  url: "http://xianqu.org"

# Build settings
exclude:
  - README.markdown
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:title
paginate: 5

# Markdown
markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - highlight
    - no_intra_emphasis
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data

# Syntax highlighter
highlighter: pygments

# Assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  # css_compressor: nil
  js_compressor:  uglifier
  cache:          true

gravatar:
  default_image: mm
  size: 100
  rating: g
  secure: true
