# Site settings
title: "Soda"                         # The title of the site.
subtitle: "Yet another Jekyll site"   # The subtile of the site.
description: "A bloggin website"      # A short description of the site.
url: "http://yourdomain.com"
baseurl: ""                           # Serve the website from the given base URL.
                                      # NOTE: you should also change assets base url if you modified this variable
logo:                                 # The logo image for the site. Put it under assets/images/ directory.
                                      # The value should be its file name, e.g. "logo.png"
cover_image:                          # The cover image path for the site.
twitter:                              # The twitter ID for the site, if you have.
google_analytics:                     # Your Google Analytics ID. e.g. "UA-XXXXX-X".
disqus_shortname:                     # Your Disqus short name, if you want to use Disqus as comment system.

# Author details. Single author currently.
author:
  name: "Your Name"
  email: "user@example.com"
  avatar:                             # If you want to use a local avatar image, put it under `assets/images/`. Otherwise, Soda uses the image from Gravatar.
  twitter:
  github:
  bio: "A short description of the author"
  url: "http://yourdomain.com"

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - rsync-exclude
  - _config_example.yml

permalink: /:year/:month/:title     # Permalink format
paginate: 5                         # Number of posts per page

# Tags and categories
category_dir: "category"            # The URL may look like this: http://yourdomain/category/this-a-category/
tag_dir: "tag"

# Put plugins here
gems:
  - jekyll-sitemap

# Markdown
markdown: redcarpet

# https://github.com/vmg/redcarpet
redcarpet:
  extensions:
    - autolink
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - highlight
    - no_intra_emphasis
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data

# Syntax highlighter
highlighter: pygments

# Excerpt
excerpt_separator: "\n\n"

# Jekyll-Assets
# https://github.com/ixti/jekyll-assets
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: /assets/                   # Be careful if the site baseurl is set.
  css_compressor: sass
  js_compressor: uglifier
  cache: true

# Gravatar
# For more details, refer to https://en.gravatar.com/site/implement/images/
gravatar:
  default_image: mm
  size: 100
  rating: g
  secure: true

# If true, we'll ignore any excerpt_separators and generate excerpt automatically. See `auto_excerpt` below.
auto_excerpt_enabled: true

# Auto excerpt configuration
# https://github.com/jorgemanrubia/truncato
auto_excerpt:
  max_length: 256
  exclude_tags: ["pre", "img", "table", "hr", "iframe", "object", "audio", "video", "embed", "h1", "h2", "h3", "h4", "h5", "h6", ".gist"]
  count_tags: false
