# Site settings
title: "Soda"
subtitle: "Yet another Jekyll site"
description: "A short description for Soda."
url: "http://yourdomain.com"
baseurl:
logo:
cover_image: "/images/site-cover-image.png"
twitter: "yiming_t"
google_analytics:
disqus_shortname:

author:
  name: "Yiming Tang"
  email: "yimingnju@gmail.com"
  avatar: "avatar.jpeg"
  twitter: "yiming_t"
  github: "yimingtang"
  bio: "I'm studying Software Engineering at Nanjing University. I'm also an iOS developer. I made <a href=\"http://lightmail.im\">LightMail</a>."
  url: "http://xianqu.org"

# Build settings
exclude:
  - README.markdown
  - Gemfile
  - Gemfile.lock
  - LICENSE

permalink: /:year/:month/:title
paginate: 5

# Tags and categories
category_dir: "category"
tag_dir: "tag"

# Plugins
gems:
  - jekyll-sitemap

# Markdown
markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - highlight
    - no_intra_emphasis
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data

# Syntax highlighter
highlighter: pygments

# Assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
  # css_compressor: nil
  js_compressor:  uglifier
  cache:          true

# Gravatar
gravatar:
  default_image: mm
  size: 100
  rating: g
  secure: true

# Excerpt
excerpt_separator: "\n\n"

# If true, we'll ignore any excerpt_separators
auto_excerpt_enabled: true

# Auto excerpt configuration
auto_excerpt:
  max_length: 256
  exclude_tags: ["pre", "img", "table", "hr", "iframe", "object", "audio", "video", "embed", "h1", "h2", "h3", "h4", "h5", "h6", ".gist"]
  count_tags: false
