# Site settings
title: "Soda"
baseurl: ""
description: "This is a site description << Soda Theme"
url: "http://yourdomain.com"
google-analytics: "UA-XXXXX-X"
license: "http://creativecommons.org/licenses/by-nc/3.0/"
twitter: "yiming_t"

author:
  name: "Yiming Tang"
  email: "yimingnju@gmail.com"
  twitter: "yiming_t"
  github: "yimingtang"
  bio: "Hi, I'm Yiming."
  url: "http://xianqu.org"


# Build settings
exclude:
  - README.markdown
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:title
paginate: 5

# Markdown
markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - highlight
    - no_intra_emphasis
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data

# Syntax highlighter
highlighter: pygments

# Assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  css_compressor: sass
  js_compressor:  uglifier
  cache:          false

gravatar:
  default_image: mm
  size: 100
  rating: g
  secure: true

